# Use this file for Matano configuration.

aws:
  account: "279476933663" # Specify the AWS account to deploy to.
  region: "us-east-2" # Specify the AWS region to deploy to.

  # Optionally, specify any tags to apply to the deployed resources.
  # tags:
  #   key: "my_tag"

