on:
  push:
    branches:
    - main

jobs:
  apply-configs:
    name: Apply configurations
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Matano
        run: |
          cd matano
          curl -OL https://github.com/matanolabs/matano/releases/download/nightly/matano-linux-x64.sh
          chmod +x matano-linux-x64.sh
          sudo ./matano-linux-x64.sh
      - name: Apply Fleet configuration
        env:
          FLEET_ADDRESS: ${{ secrets.FLEET_ADDRESS }}
          FLEET_TOKEN: ${{ secrets.FLEET_TOKEN }}
        run: |
          cd fleet
          ./apply-queries.sh
      - name: Apply Matano configuration
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd matano
          matano deploy
